export const TrackingZonesData = [
    {
        key: 1,
        value: 'zone1',
        label: 'Zone 1',
    },
    {
        key: 2,
        value: 'zone2',
        label: 'Zone 2',
    },
    {
        key: 3,
        value: 'zone3',
        label: 'Zone 3',
    },
    {
        key: 4,
        value: 'zone4',
        label: 'Zone 4',
    },
    {
        key: 5,
        value: 'zone5',
        label: 'Zone 5',
    },
];

export const RoadsZones = [
    {
        key: 1,
        value: 'zone1',
        label: 'Zone 1',
    },
    {
        key: 2,
        value: 'zone2',
        label: 'Zone 2',
    },
    {
        key: 3,
        value: 'zone3',
        label: 'Zone 3',
    },
    {
        key: 4,
        value: 'zone4',
        label: 'Zone 4',
    },
    {
        key: 5,
        value: 'zone5',
        label: 'Zone 5',
    },
    {
        key: 6,
        value: 'outside',
        label: 'Outside',
    },
];

export const Trackers = [
    {
        id: 'Z1-0001',
        location: 'Islamabad',
        zone: 'zone 1',
        sector: 'f6',
        lastUpdated: '10/8/2023',
        change: false,
        dateOfChange: 'none',
        changePercent: 'none',
        validity: '20/10/2024',
    },
    {
        id: 'Z2-0002',
        location: 'Islamabad',
        zone: 'zone 2',
        sector: 'f6',
        lastUpdated: '10/8/2023',
        change: true,
        dateOfChange: '20/02/2023',
        changePercent: '18%',
        validity: '20/10/2024',
        
    },
    {
        id: 'Z4-0003',
        location: 'Islamabad',
        zone: 'zone 4',
        sector: 'f6',
        lastUpdated: '10/8/2023',
        change: false,
        dateOfChange: 'none',
        changePercent: 'none',
        validity: '20/10/2024',
    },
    {
        id: 'Z5-0004',
        location: 'Islamabad',
        zone: 'zone 5',
        sector: 'f6',
        lastUpdated: '10/8/2023',
        change: false,
        dateOfChange: 'none',
        changePercent: 'none',
        validity: '20/10/2024',
    },
    {
        id: 'Z3-0005',
        location: 'street 46, f6, Main Markaz, Islamabad, Pakistan',
        zone: 'zone 3',
        sector: 'f6',
        lastUpdated: '10/8/2023',
        change: true,
        dateOfChange: '10/8/2023',
        changePercent: '5%',
        validity: '20/10/2024',
    },
    {
        id: 'Z1-0006',
        location: 'Islamabad',
        zone: 'zone 1',
        sector: 'f6',
        lastUpdated: '10/8/2023',
        change: false,
        dateOfChange: 'none',
        changePercent: 'none',
        validity: '20/10/2024',
    },
];

export const supportAlerts = [
    {
        sender: 'user1023',
        userEmail: 'user@gmail.com',
        description: 'I have been facing problem in accessing my credits for generating construction plan decription, kindly fix it.',
        date: '20/10/2023',
        subject: 'Construction plan problem',
        type: 'report',
        rating: 3,
    },
    {
        sender: 'user1023',
        userEmail: 'user@gmail.com',
        description: 'I have been facing problem in accessing my credits for generating construction plan decription, kindly fix it.',
        date: '20/10/2023',
        subject: 'Construction plan problem',
        type: 'feedback',
        rating: 4,
    },
    {
        sender: 'user1023',
        userEmail: 'user@gmail.com',
        description: 'I have been facing problem in accessing my credits for generating construction plan decription, kindly fix it.',
        date: '20/10/2023',
        subject: 'Construction plan problem',
        type: 'report',
        rating: 5,
    },
    {
        sender: 'user1023',
        userEmail: 'user@gmail.com',
        description: 'I have been facing problem in accessing my credits for generating construction plan decription, kindly fix it.',
        date: '20/10/2023',
        subject: 'Construction plan problem',
        type: 'feedback',
        rating: 3.5,
    },
    {
        sender: 'user1023',
        userEmail: 'user@gmail.com',
        description: 'I have been facing problem in accessing my credits for generating construction plan decription, kindly fix it.',
        date: '20/10/2023',
        subject: 'Construction plan problem',
        type: 'report',
        rating: 4,
    },
    {
        sender: 'user1023',
        userEmail: 'user@gmail.com',
        description: 'I have been facing problem in accessing my credits for generating construction plan decription, kindly fix it.',
        date: '20/10/2023',
        subject: 'Construction plan problem',
        type: 'feedback',
        rating: 3.5,
    },
    {
        sender: 'user1023',
        userEmail: 'user@gmail.com',
        description: 'I have been facing problem in accessing my credits for generating construction plan decription, kindly fix it.',
        date: '20/10/2023',
        subject: 'Construction plan problem',
        type: 'feedback',
        rating: 5,
    },
];